"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { request } from "@/lib/api";
import { encodeTokenBalanceOf, encodeTokenTransfer, ethereumProvider, parseHexInteger, switchWalletNetwork, waitForTransaction } from "@/lib/wallet";
import type { Property, User } from "@/types";

type Health={backend:string;postgresql:string;blockchain:string;chain_id:number|null;current_block:number|null;landchain_contract_address:string|null};
const nav=["Dashboard","Users","Register Property","Property Explorer","Verify Property","Ownership Transfer","Tokenize Asset","Token Portfolio","Token Transfer"];
const short=(s?:string|null)=>s?`${s.slice(0,7)}…${s.slice(-5)}`:"—";
const networkName=(chainId?:number|null)=>chainId===11155111?"Sepolia testnet":chainId===31337?"Local Hardhat":chainId?`Chain ${chainId}`:"Network unavailable";
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="label">{label}</span>{children}</label>}
function Input(props:React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={`field ${props.className||""}`} />}
function Select({children,...props}:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...props} className="field">{children}</select>}
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="glass rounded-2xl p-6"><div className="mb-5"><h2 className="text-lg font-semibold">{title}</h2>{subtitle&&<p className="mt-1 text-sm muted">{subtitle}</p>}</div>{children}</section>}

export default function Home(){
 const [section,setSection]=useState("Dashboard"),[health,setHealth]=useState<Health|null>(null),[users,setUsers]=useState<User[]>([]),[properties,setProperties]=useState<Property[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState<{kind:"ok"|"error";text:string}|null>(null),[result,setResult]=useState<any>(null);
 const [documentHash,setDocumentHash]=useState(""),[documentName,setDocumentName]=useState(""),[hashing,setHashing]=useState(false);
 const [walletAddress,setWalletAddress]=useState<string|null>(null),[walletChainId,setWalletChainId]=useState<number|null>(null),[walletBusy,setWalletBusy]=useState(false);
 const activeNetwork=networkName(health?.chain_id);
 const refresh=useCallback(async()=>{try{const [h,u,p]=await Promise.all([request<Health>("/health"),request<User[]>("/users"),request<Property[]>("/properties")]);setHealth(h);setUsers(u);setProperties(p)}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"API unavailable"})}},[]);
 useEffect(()=>{refresh();const id=setInterval(refresh,12000);return()=>clearInterval(id)},[refresh]);
 useEffect(()=>{if(!window.ethereum)return;const onAccounts=(value:unknown)=>{const accounts=Array.isArray(value)?value:[];setWalletAddress(typeof accounts[0]==="string"?accounts[0]:null)};const onChain=(value:unknown)=>{try{setWalletChainId(Number(BigInt(String(value))))}catch{setWalletChainId(null)}};window.ethereum.on?.("accountsChanged",onAccounts);window.ethereum.on?.("chainChanged",onChain);return()=>{window.ethereum?.removeListener?.("accountsChanged",onAccounts);window.ethereum?.removeListener?.("chainChanged",onChain)}},[]);
 const run=async(action:()=>Promise<any>,message:string)=>{setLoading(true);setNotice(null);setResult(null);try{const data=await action();setResult(data);setNotice({kind:"ok",text:message});await refresh()}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Request failed"})}finally{setLoading(false)}};
 const propertyOptions=useMemo(()=>properties.map(p=><option key={p.property_id} value={p.property_id}>#{p.property_id} · {p.title}</option>),[properties]);
 const userOptions=useMemo(()=>users.map(u=><option key={u.id} value={u.id}>{u.full_name} · {short(u.wallet_address)}</option>),[users]);
 const navIcon=["◈","♙","＋","⌕","✓","⇄","◇","▦","↗"];
 const stat=(label:string,value:number|string,detail:string,icon:string)=><div className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-sm muted">{label}</span><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-100 text-lg text-emerald-700">{icon}</span></div><div className="mt-5 text-3xl font-semibold">{value}</div><div className="mt-1 text-xs muted">{detail}</div></div>;
 const propSelect=(label="Property")=><Field label={label}><Select name="property_id" required defaultValue="">{properties.length===0?<option value="">No properties yet</option>:<option value="" disabled>Select a property</option>}{propertyOptions}</Select></Field>;
 const userSelect=()=><Field label="Owner"><Select name="owner_user_id" required defaultValue=""><option value="" disabled>Select owner</option>{userOptions}</Select></Field>;
 const handle=(e:React.FormEvent<HTMLFormElement>,fn:(fd:FormData)=>Promise<any>,message:string)=>{e.preventDefault();const fd=new FormData(e.currentTarget);void run(()=>fn(fd),message)};
 const submit=(path:string,body:any,method="POST")=>request(path,{method,body:method==="GET"?undefined:JSON.stringify(body)});
 const connectWallet=async()=>{setWalletBusy(true);setNotice(null);try{const wallet=ethereumProvider();if(!health?.chain_id)throw new Error("The application has not loaded its blockchain network yet. Try again shortly.");const requested=await wallet.request({method:"eth_requestAccounts"});const accounts=Array.isArray(requested)?requested:[];if(typeof accounts[0]!=="string")throw new Error("MetaMask did not return an account. Unlock it and try again.");let chainId=Number(parseHexInteger(await wallet.request({method:"eth_chainId"})));if(chainId!==health.chain_id){await switchWalletNetwork(wallet,health.chain_id);chainId=Number(parseHexInteger(await wallet.request({method:"eth_chainId"})));}if(chainId!==health.chain_id)throw new Error(`Switch MetaMask to ${networkName(health.chain_id)} before transferring.`);setWalletAddress(accounts[0]);setWalletChainId(chainId);setNotice({kind:"ok",text:`Wallet connected: ${short(accounts[0])} on ${networkName(chainId)}.`})}catch(error){setNotice({kind:"error",text:error instanceof Error?error.message:"Could not connect MetaMask."})}finally{setWalletBusy(false)}};
 const transferFromWallet=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setLoading(true);setNotice(null);setResult(null);try{const wallet=ethereumProvider();const form=new FormData(event.currentTarget);const propertyId=Number(form.get("property_id"));const property=properties.find(item=>item.property_id===propertyId&&item.tokenized);if(!property?.token_contract_address)throw new Error("Choose a property that has been tokenized.");const recipient=String(form.get("recipient")||"").trim();if(!/^0x[a-fA-F0-9]{40}$/.test(recipient))throw new Error("Enter a valid recipient wallet address.");const rawAmount=String(form.get("amount")||"");if(!/^[1-9][0-9]*$/.test(rawAmount))throw new Error("Enter a positive whole number of tokens.");const amount=BigInt(rawAmount);const accounts=await wallet.request({method:"eth_accounts"});const connected=Array.isArray(accounts)?accounts[0]:null;if(typeof connected!=="string"||!walletAddress||connected.toLowerCase()!==walletAddress.toLowerCase())throw new Error("Connect the wallet that owns the tokens, then try again.");const currentChain=Number(parseHexInteger(await wallet.request({method:"eth_chainId"})));if(currentChain!==health?.chain_id)throw new Error(`Switch MetaMask to ${networkName(health?.chain_id)} before transferring.`);const readBalance=async(address:string)=>parseHexInteger(await wallet.request({method:"eth_call",params:[{to:property.token_contract_address,data:encodeTokenBalanceOf(address)},"latest"]}));const previousBalance=await readBalance(connected);const recipientPreviousBalance=await readBalance(recipient);if(previousBalance<amount)throw new Error(`Insufficient token balance. This wallet has ${previousBalance.toString()} tokens.`);const response=await wallet.request({method:"eth_sendTransaction",params:[{from:connected,to:property.token_contract_address,data:encodeTokenTransfer(recipient,amount)}]});if(typeof response!=="string"||!/^0x[a-fA-F0-9]{64}$/.test(response))throw new Error("MetaMask did not return a valid transaction hash.");const transactionHash=response;setNotice({kind:"ok",text:"Transaction submitted. Confirm it in MetaMask and wait for Sepolia confirmation."});await waitForTransaction(wallet,transactionHash);const newBalance=await readBalance(connected);const recipientNewBalance=await readBalance(recipient);setResult({property_id:propertyId,token_contract_address:property.token_contract_address,sender:connected,recipient,amount:rawAmount,previous_balance:previousBalance.toString(),new_balance:newBalance.toString(),recipient_previous_balance:recipientPreviousBalance.toString(),recipient_new_balance:recipientNewBalance.toString(),transaction_hash:transactionHash,status:"confirmed",signed_by:"MetaMask"});setNotice({kind:"ok",text:"Token transfer confirmed on Sepolia."});await refresh()}catch(error){setNotice({kind:"error",text:error instanceof Error?error.message:"Token transfer failed."})}finally{setLoading(false)}};
 const transferSelect=(label="Property")=><Field label={label}><Select name="property_id" required defaultValue=""><option value="" disabled>Select a property</option>{propertyOptions}</Select></Field>;
 const row=(p:Property)=><tr key={p.id}><td className="font-medium">#{p.property_id}</td><td>{p.title}</td><td>{p.location_address}</td><td><span className="badge">{p.blockchain_verified?"Verified":"Unverified"}</span></td><td><span className="badge">{p.tokenized?"Tokenized":"—"}</span></td></tr>;

 return <div className="min-h-screen lg:flex">
  <aside className="w-full border-b border-slate-200 bg-white/95 px-4 py-4 lg:fixed lg:inset-y-0 lg:w-[250px] lg:border-b-0 lg:border-r lg:border-slate-200 lg:px-5 lg:py-7">
   <div className="mb-7 flex items-center gap-3 px-2"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-emerald-500 via-teal-500 to-amber-400 text-xl font-bold">L</div><div><div className="font-semibold tracking-wide">LandChain</div><div className="text-[10px] uppercase tracking-[.2em] text-emerald-700">Property ledger</div></div></div>
   <nav className="flex gap-1 overflow-x-auto lg:flex-col">{nav.map((item,i)=><button key={item} onClick={()=>{setSection(item);setNotice(null);setResult(null)}} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${section===item?"bg-emerald-100 text-emerald-800":"text-slate-600 hover:bg-slate-100 hover:text-slate-900"}`}><span className="w-5 text-center">{navIcon[i]}</span>{item}</button>)}</nav>
   <div className="mt-8 hidden rounded-xl border border-slate-200 bg-slate-50 p-4 lg:block"><div className="mb-2 text-[10px] uppercase tracking-[.16em] muted">Network</div><div className="flex items-center gap-2 text-sm"><span className={`h-2 w-2 rounded-full ${health?.blockchain==="connected"?"bg-emerald-400":"bg-rose-400"}`} />{health?.blockchain||"Connecting"}</div><div className="mt-2 text-xs muted">Chain {health?.chain_id??"—"}</div></div>
  </aside>
  <main className="min-w-0 flex-1 px-4 py-7 sm:px-7 lg:ml-[250px] lg:px-10 lg:py-9">
   <header className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 text-xs uppercase tracking-[.2em] text-emerald-700">Real estate · On-chain registry</div><h1 className="text-3xl font-semibold tracking-tight">{section}</h1><p className="mt-2 text-sm muted">Manage property ownership, verification and fractional shares.</p></div><button className="badge cursor-pointer" onClick={()=>void refresh()}>⟳ &nbsp;Refresh data</button></header>
   {notice&&<div className={`mb-5 rounded-xl border px-4 py-3 text-sm ${notice.kind==="ok"?"border-emerald-400/20 bg-emerald-100 text-emerald-800":"border-rose-400/20 bg-rose-400/10 text-rose-800"}`}>{notice.kind==="ok"?"✓  ":"!  "}{notice.text}</div>}
   {result&&<div className="glass mb-5 rounded-xl p-4"><div className="mb-2 text-xs uppercase tracking-widest text-emerald-700">Confirmed result</div><pre className="overflow-auto whitespace-pre-wrap break-all text-xs text-slate-700">{JSON.stringify(result,null,2)}</pre>{typeof result.transaction_hash==="string"&&<a className="mt-3 inline-block text-sm font-medium text-emerald-800 underline" href={`https://sepolia.etherscan.io/tx/${result.transaction_hash}`} target="_blank" rel="noreferrer">View transaction on Sepolia Etherscan ↗</a>}</div>}
   {section==="Dashboard"&&<div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stat("Registered Properties",properties.length,health?.postgresql==="connected"?"Recorded in PostgreSQL":"Database records","⌂")}{stat("Verified Properties",properties.filter(p=>p.blockchain_verified).length,"Confirmed on-chain","✓")}{stat("Tokenized Assets",properties.filter(p=>p.tokenized).length,"Fractional assets","◇")}{stat("System Users",users.length,"Registered participants","♙")}</div><Panel title="System status" subtitle="Live checks from your connected API, database, and blockchain"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[["FastAPI",health?.backend],["PostgreSQL",health?.postgresql==="not_postgresql"?"PostgreSQL is not configured":health?.postgresql],["Blockchain",health?.blockchain],["Current block",health?.current_block],["Network",activeNetwork],["LandChain contract",health?.landchain_contract_address]].map(([k,v])=><div key={String(k)} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="text-xs muted">{k}</div><div className="mt-2 break-all text-sm font-medium">{v??"Unavailable"}</div></div>)}</div></Panel><Panel title="Recent properties" subtitle="Database records and latest sync flags"><div className="table-wrap"><table className="w-full"><thead><tr><th>ID</th><th>Property</th><th>Location</th><th>Verification</th><th>Tokens</th></tr></thead><tbody>{properties.length?properties.slice(0,6).map(row):<tr><td colSpan={5} className="py-8 text-center muted">No properties registered yet.</td></tr>}</tbody></table></div></Panel></div>}
   {section==="Users"&&<div className="grid gap-6 xl:grid-cols-[minmax(320px,.8fr)_1.2fr]"><Panel title="Add user" subtitle="Create a participant and link their wallet"><form className="space-y-4" onSubmit={e=>handle(e,fd=>submit("/users",{full_name:fd.get("full_name"),email:fd.get("email"),wallet_address:fd.get("wallet_address"),role:fd.get("role")}),"User created.")}><Field label="Full Name"><Input name="full_name" required placeholder="Alex Morgan"/></Field><Field label="Email"><Input name="email" type="email" required placeholder="alex@example.com"/></Field><Field label="Wallet Address"><Input name="wallet_address" required placeholder="0x…"/></Field><Field label="Role"><Select name="role"><option>Investor</option><option>Owner</option><option>Administrator</option></Select></Field><button className="btn w-full" disabled={loading}>{loading?"Creating…":"Create User"}</button></form></Panel><Panel title="System users" subtitle={`${users.length} registered participants`}><div className="table-wrap"><table className="w-full"><thead><tr><th>Name</th><th>Email</th><th>Wallet</th><th>Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.email}</td><td title={u.wallet_address}>{short(u.wallet_address)}</td><td><span className="badge">{u.role}</span></td></tr>)}</tbody></table></div></Panel></div>}
   {section==="Register Property"&&<Panel title="Register a property" subtitle="On-chain ownership is registered first. Database state is saved after confirmation."><form className="grid gap-4 md:grid-cols-2" onSubmit={e=>handle(e,fd=>submit("/properties/register",{property_id:Number(fd.get("property_id")),owner_user_id:Number(fd.get("owner_user_id")),title:fd.get("title"),location_address:fd.get("location_address"),area_sq_ft:Number(fd.get("area_sq_ft")),property_value:Number(fd.get("property_value")),land_reference_code:fd.get("land_reference_code"),document_hash:documentHash}),"Property registered and confirmed on-chain.")}><Field label="Property ID"><Input name="property_id" type="number" min="1" required placeholder="1001"/></Field>{userSelect()}<Field label="Title"><Input name="title" required placeholder="Riverside Apartments"/></Field><Field label="Location"><Input name="location_address" required placeholder="Full property address"/></Field><Field label="Area (sq ft)"><Input name="area_sq_ft" type="number" min="1" step="any" required/></Field><Field label="Property Value"><Input name="property_value" type="number" min="0.01" step="0.01" required/></Field><Field label="Land Reference Code"><Input name="land_reference_code" required placeholder="LAND-MH-1001"/></Field><div className="md:col-span-2 grid gap-4 md:grid-cols-2"><Field label="Property Document"><Input name="document_file" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" required onChange={async event=>{const input=event.currentTarget;const file=input.files?.[0];setDocumentHash("");setDocumentName(file?.name||"");setNotice(null);if(!file)return;if(file.size>25*1024*1024){setDocumentName("");input.value="";setNotice({kind:"error",text:"Choose a document smaller than 25 MB."});return;}setHashing(true);try{if(!globalThis.crypto?.subtle)throw new Error("Secure hashing is unavailable");const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());setDocumentHash(Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join(""));}catch{setDocumentName("");input.value="";setNotice({kind:"error",text:"Could not hash this document in the browser. Try a smaller file or a secure browser connection."});}finally{setHashing(false);}}}/></Field><Field label="Document Hash (SHA-256)"><Input name="document_hash_preview" value={documentHash} readOnly required placeholder={hashing?"Calculating hash…":"Select a document to generate its hash"}/></Field><p className="text-xs muted md:col-span-2">{documentName?`Selected: ${documentName}. `:""}The file stays on this device; only its hash is sent to the database and blockchain.</p></div><div className="md:col-span-2"><button className="btn" disabled={loading||hashing||!documentHash}>{hashing?"Calculating document hash…":loading?"Submitting · Waiting for confirmation…":"Register Property"}</button></div></form></Panel>}
   {section==="Property Explorer"&&<Panel title="Property explorer" subtitle="Compare live PostgreSQL records with the current LandChain deployment"><form className="mb-6 flex max-w-xl gap-3" onSubmit={e=>handle(e,fd=>request(`/properties/${fd.get("property_id")}/inspect`),"Inspection completed.")}><Input name="property_id" type="number" min="1" required placeholder="Property ID, e.g. 1001"/><button className="btn shrink-0" disabled={loading}>Inspect</button></form>{properties.length>0&&<div className="table-wrap"><table className="w-full"><thead><tr><th>ID</th><th>Property</th><th>Location</th><th>Verification</th><th>Tokens</th></tr></thead><tbody>{properties.map(row)}</tbody></table></div>}<p className="mt-4 text-xs muted">Results list the exact fields that differ when database and chain state are inconsistent.</p></Panel>}
   {section==="Verify Property"&&<Panel title="Verify property" subtitle="Verification is committed on-chain before PostgreSQL is updated"><div className="mb-5 rounded-xl border border-slate-200"><div className="table-wrap"><table className="w-full"><thead><tr><th>ID</th><th>Property</th><th>Owner</th><th>Action</th></tr></thead><tbody>{properties.filter(p=>p.blockchain_registered&&!p.blockchain_verified).map(p=><tr key={p.id}><td>#{p.property_id}</td><td>{p.title}</td><td>{users.find(u=>u.id===p.owner_user_id)?.full_name||"—"}</td><td><button className="btn !px-3 !py-2 text-xs" disabled={loading} onClick={()=>void run(()=>submit(`/properties/${p.property_id}/verify`,{}),`Property #${p.property_id} verified.`)}>Verify</button></td></tr>)}</tbody></table></div>{!properties.some(p=>p.blockchain_registered&&!p.blockchain_verified)&&<div className="p-6 text-center text-sm muted">No registered unverified properties.</div>}</div></Panel>}
   {section==="Ownership Transfer"&&<Panel title="Transfer property ownership" subtitle="Backend signer must match the current blockchain owner"><form className="grid max-w-2xl gap-4 md:grid-cols-2" onSubmit={e=>handle(e,fd=>submit(`/properties/${fd.get("property_id")}/transfer`,{new_owner:fd.get("new_owner")}),"Ownership transferred on-chain and synchronized.")}>{transferSelect()}<Field label="New Owner Address"><Input name="new_owner" required placeholder="Registered user's wallet address"/></Field><div><button className="btn" disabled={loading}>{loading?"Transferring…":"Transfer Ownership"}</button></div></form></Panel>}
   {section==="Tokenize Asset"&&<Panel title="Tokenize verified property" subtitle="Deploy a property-specific ERC-20 contract with whole-number shares"><form className="grid max-w-3xl gap-4 md:grid-cols-2" onSubmit={e=>handle(e,fd=>submit(`/properties/${fd.get("property_id")}/tokenize`,{token_name:fd.get("token_name"),symbol:fd.get("symbol"),total_supply:Number(fd.get("total_supply")),price_per_token:Number(fd.get("price_per_token"))}),"Token deployed and saved.")}>{propSelect("Verified Property")}<Field label="Token Name"><Input name="token_name" required placeholder="Riverside Shares"/></Field><Field label="Token Symbol"><Input name="symbol" required maxLength={16} placeholder="RIV"/></Field><Field label="Total Supply"><Input name="total_supply" type="number" min="1" step="1" required placeholder="10000"/></Field><Field label="Price Per Token"><Input name="price_per_token" type="number" min="0.01" step="0.01" required placeholder="250"/></Field><div><button className="btn" disabled={loading}>{loading?"Deploying token…":"Tokenize Property"}</button></div></form></Panel>}
   {section==="Token Portfolio"&&<Panel title="Token portfolio" subtitle="Read the current wallet balance directly from the token contract"><form className="mb-6 grid max-w-2xl gap-4 md:grid-cols-[1fr_1fr_auto]" onSubmit={e=>handle(e,fd=>request(`/tokens/${fd.get("property_id")}/balance?wallet=${encodeURIComponent(String(fd.get("wallet")))}`),"Balance loaded from blockchain.")}>{transferSelect()}<Field label="Wallet Address"><Input name="wallet" required placeholder="0x…"/></Field><button className="btn self-end" disabled={loading}>Check Balance</button></form><div className="grid gap-4 sm:grid-cols-2">{properties.filter(p=>p.tokenized).map(p=><div key={p.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="text-xs muted">Property #{p.property_id}</div><div className="mt-1 font-medium">{p.title}</div><div className="mt-3 break-all text-xs text-emerald-800">{p.token_contract_address}</div></div>)}</div></Panel>}
   {section==="Token Transfer"&&<Panel title="Transfer property tokens" subtitle="Connect the wallet that owns the tokens. MetaMask signs the transfer; LandChain never receives its private key."><div className="mb-5 flex flex-wrap items-center gap-3"><button type="button" className="btn" onClick={()=>void connectWallet()} disabled={walletBusy||!health?.chain_id}>{walletBusy?"Connecting…":walletAddress?"Reconnect MetaMask":"Connect MetaMask"}</button>{walletAddress&&<div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm"><span className="font-medium">{short(walletAddress)}</span><span className="ml-2 muted">{walletChainId===health?.chain_id?networkName(walletChainId):"Wrong network"}</span><button type="button" className="ml-3 text-xs text-emerald-800 underline" onClick={()=>{setWalletAddress(null);setWalletChainId(null)}}>Disconnect</button></div>}</div><form className="grid max-w-3xl gap-4 md:grid-cols-2" onSubmit={transferFromWallet}><Field label="Tokenized Property"><Select name="property_id" required defaultValue=""><option value="" disabled>Select a tokenized property</option>{properties.filter(property=>property.tokenized&&property.token_contract_address).map(property=><option key={property.property_id} value={property.property_id}>#{property.property_id} · {property.title}</option>)}</Select></Field><Field label="Sender (connected wallet)"><Input value={walletAddress||"Connect MetaMask first"} readOnly/></Field><Field label="Recipient Wallet Address"><Input name="recipient" required placeholder="0x…"/></Field><Field label="Amount (whole tokens)"><Input name="amount" type="number" min="1" step="1" required placeholder="100"/></Field><div className="md:col-span-2"><button className="btn" disabled={loading||!walletAddress||walletChainId!==health?.chain_id}>{loading?"Waiting for MetaMask and Sepolia confirmation…":"Review and Transfer Tokens"}</button></div></form><p className="mt-4 text-xs muted">MetaMask will show the token contract and ask you to approve the transaction. Check the recipient and amount before confirming. You need Sepolia ETH in the connected wallet for the network fee.</p></Panel>}
   <footer className="mt-10 flex flex-wrap justify-between gap-3 border-t border-slate-200 pt-5 text-xs muted"><span>LandChain · {activeNetwork}</span><span>API {health?.backend==="ok"?"● Online":"○ Offline"}</span></footer>
  </main>
 </div>
}
