"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { request } from "@/lib/api";
import type { Property, User } from "@/types";

type Health={backend:string;postgresql:string;blockchain:string;chain_id:number|null;current_block:number|null;landchain_contract_address:string|null};
const nav=["Dashboard","Users","Register Property","Property Explorer","Verify Property","Ownership Transfer","Tokenize Asset","Token Portfolio","Token Transfer"];
const short=(s?:string|null)=>s?`${s.slice(0,7)}…${s.slice(-5)}`:"—";
const networkName=(chainId?:number|null)=>chainId===11155111?"Sepolia testnet":chainId===31337?"Local Hardhat":chainId?`Chain ${chainId}`:"Network unavailable";
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="label">{label}</span>{children}</label>}
function Input(props:React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={`field ${props.className||""}`} />}
function Select({children,...props}:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...props} className="field">{children}</select>}
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="glass rounded-2xl p-6"><div className="mb-5"><h2 className="text-lg font-semibold">{title}</h2>{subtitle&&<p className="mt-1 text-sm muted">{subtitle}</p>}</div>{children}</section>}

export default function Home(){
 const [section,setSection]=useState("Dashboard"),[health,setHealth]=useState<Health|null>(null),[users,setUsers]=useState<User[]>([]),[properties,setProperties]=useState<Property[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState<{kind:"ok"|"error";text:string}|null>(null),[result,setResult]=useState<any>(null);
 const [documentHash,setDocumentHash]=useState(""),[documentName,setDocumentName]=useState(""),[hashing,setHashing]=useState(false);
 const activeNetwork=networkName(health?.chain_id);
 const refresh=useCallback(async()=>{try{const [h,u,p]=await Promise.all([request<Health>("/health"),request<User[]>("/users"),request<Property[]>("/properties")]);setHealth(h);setUsers(u);setProperties(p)}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"API unavailable"})}},[]);
 useEffect(()=>{refresh();const id=setInterval(refresh,12000);return()=>clearInterval(id)},[refresh]);
 const run=async(action:()=>Promise<any>,message:string)=>{setLoading(true);setNotice(null);setResult(null);try{const data=await action();setResult(data);setNotice({kind:"ok",text:message});await refresh()}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Request failed"})}finally{setLoading(false)}};
 const propertyOptions=useMemo(()=>properties.map(p=><option key={p.property_id} value={p.property_id}>#{p.property_id} · {p.title}</option>),[properties]);
 const userOptions=useMemo(()=>users.map(u=><option key={u.id} value={u.id}>{u.full_name} · {short(u.wallet_address)}</option>),[users]);
 const navIcon=["◈","♙","＋","⌕","✓","⇄","◇","▦","↗"];
 const stat=(label:string,value:number|string,detail:string,icon:string)=><div className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-sm muted">{label}</span><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-400/10 text-lg text-emerald-300">{icon}</span></div><div className="mt-5 text-3xl font-semibold">{value}</div><div className="mt-1 text-xs muted">{detail}</div></div>;
 const propSelect=(label="Property")=><Field label={label}><Select name="property_id" required defaultValue="">{properties.length===0?<option value="">No properties yet</option>:<option value="" disabled>Select a property</option>}{propertyOptions}</Select></Field>;
 const userSelect=()=><Field label="Owner"><Select name="owner_user_id" required defaultValue=""><option value="" disabled>Select owner</option>{userOptions}</Select></Field>;
 const handle=(e:React.FormEvent<HTMLFormElement>,fn:(fd:FormData)=>Promise<any>,message:string)=>{e.preventDefault();const fd=new FormData(e.currentTarget);void run(()=>fn(fd),message)};
 const submit=(path:string,body:any,method="POST")=>request(path,{method,body:method==="GET"?undefined:JSON.stringify(body)});
 const transferSelect=(label="Property")=><Field label={label}><Select name="property_id" required defaultValue=""><option value="" disabled>Select a property</option>{propertyOptions}</Select></Field>;
 const row=(p:Property)=><tr key={p.id}><td className="font-medium">#{p.property_id}</td><td>{p.title}</td><td>{p.location_address}</td><td><span className="badge">{p.blockchain_verified?"Verified":"Unverified"}</span></td><td><span className="badge">{p.tokenized?"Tokenized":"—"}</span></td></tr>;

 return <div className="min-h-screen lg:flex">
  <aside className="w-full border-b border-white/5 bg-[#08110f]/80 px-4 py-4 lg:fixed lg:inset-y-0 lg:w-[250px] lg:border-b-0 lg:border-r lg:border-white/5 lg:px-5 lg:py-7">
   <div className="mb-7 flex items-center gap-3 px-2"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-emerald-500 via-teal-500 to-amber-400 text-xl font-bold">L</div><div><div className="font-semibold tracking-wide">LandChain</div><div className="text-[10px] uppercase tracking-[.2em] text-emerald-300">Property ledger</div></div></div>
   <nav className="flex gap-1 overflow-x-auto lg:flex-col">{nav.map((item,i)=><button key={item} onClick={()=>{setSection(item);setNotice(null);setResult(null)}} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${section===item?"bg-emerald-400/15 text-emerald-200":"text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className="w-5 text-center">{navIcon[i]}</span>{item}</button>)}</nav>
   <div className="mt-8 hidden rounded-xl border border-white/5 bg-white/[.025] p-4 lg:block"><div className="mb-2 text-[10px] uppercase tracking-[.16em] muted">Network</div><div className="flex items-center gap-2 text-sm"><span className={`h-2 w-2 rounded-full ${health?.blockchain==="connected"?"bg-emerald-400":"bg-rose-400"}`} />{health?.blockchain||"Connecting"}</div><div className="mt-2 text-xs muted">Chain {health?.chain_id??"—"}</div></div>
  </aside>
  <main className="min-w-0 flex-1 px-4 py-7 sm:px-7 lg:ml-[250px] lg:px-10 lg:py-9">
   <header className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 text-xs uppercase tracking-[.2em] text-emerald-300">Real estate · On-chain registry</div><h1 className="text-3xl font-semibold tracking-tight">{section}</h1><p className="mt-2 text-sm muted">Manage property ownership, verification and fractional shares.</p></div><button className="badge cursor-pointer" onClick={()=>void refresh()}>⟳ &nbsp;Refresh data</button></header>
   {notice&&<div className={`mb-5 rounded-xl border px-4 py-3 text-sm ${notice.kind==="ok"?"border-emerald-400/20 bg-emerald-400/10 text-emerald-200":"border-rose-400/20 bg-rose-400/10 text-rose-200"}`}>{notice.kind==="ok"?"✓  ":"!  "}{notice.text}</div>}
   {result&&<div className="glass mb-5 rounded-xl p-4"><div className="mb-2 text-xs uppercase tracking-widest text-emerald-300">Confirmed result</div><pre className="overflow-auto whitespace-pre-wrap break-all text-xs text-slate-300">{JSON.stringify(result,null,2)}</pre></div>}
   {section==="Dashboard"&&<div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stat("Registered Properties",properties.length,health?.postgresql==="connected"?"Recorded in PostgreSQL":"Database records","⌂")}{stat("Verified Properties",properties.filter(p=>p.blockchain_verified).length,"Confirmed on-chain","✓")}{stat("Tokenized Assets",properties.filter(p=>p.tokenized).length,"Fractional assets","◇")}{stat("System Users",users.length,"Registered participants","♙")}</div><Panel title="System status" subtitle="Live checks from your connected API, database, and blockchain"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[["FastAPI",health?.backend],["PostgreSQL",health?.postgresql==="not_postgresql"?"PostgreSQL is not configured":health?.postgresql],["Blockchain",health?.blockchain],["Current block",health?.current_block],["Network",activeNetwork],["LandChain contract",health?.landchain_contract_address]].map(([k,v])=><div key={String(k)} className="rounded-xl border border-white/5 bg-white/[.025] p-4"><div className="text-xs muted">{k}</div><div className="mt-2 break-all text-sm font-medium">{v??"Unavailable"}</div></div>)}</div></Panel><Panel title="Recent properties" subtitle="Database records and latest sync flags"><div className="table-wrap"><table className="w-full"><thead><tr><th>ID</th><th>Property</th><th>Location</th><th>Verification</th><th>Tokens</th></tr></thead><tbody>{properties.length?properties.slice(0,6).map(row):<tr><td colSpan={5} className="py-8 text-center muted">No properties registered yet.</td></tr>}</tbody></table></div></Panel></div>}
   {section==="Users"&&<div className="grid gap-6 xl:grid-cols-[minmax(320px,.8fr)_1.2fr]"><Panel title="Add user" subtitle="Create a participant and link their wallet"><form className="space-y-4" onSubmit={e=>handle(e,fd=>submit("/users",{full_name:fd.get("full_name"),email:fd.get("email"),wallet_address:fd.get("wallet_address"),role:fd.get("role")}),"User created.")}><Field label="Full Name"><Input name="full_name" required placeholder="Alex Morgan"/></Field><Field label="Email"><Input name="email" type="email" required placeholder="alex@example.com"/></Field><Field label="Wallet Address"><Input name="wallet_address" required placeholder="0x…"/></Field><Field label="Role"><Select name="role"><option>Investor</option><option>Owner</option><option>Administrator</option></Select></Field><button className="btn w-full" disabled={loading}>{loading?"Creating…":"Create User"}</button></form></Panel><Panel title="System users" subtitle={`${users.length} registered participants`}><div className="table-wrap"><table className="w-full"><thead><tr><th>Name</th><th>Email</th><th>Wallet</th><th>Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.email}</td><td title={u.wallet_address}>{short(u.wallet_address)}</td><td><span className="badge">{u.role}</span></td></tr>)}</tbody></table></div></Panel></div>}
   {section==="Register Property"&&<Panel title="Register a property" subtitle="On-chain ownership is registered first. Database state is saved after confirmation."><form className="grid gap-4 md:grid-cols-2" onSubmit={e=>handle(e,fd=>submit("/properties/register",{property_id:Number(fd.get("property_id")),owner_user_id:Number(fd.get("owner_user_id")),title:fd.get("title"),location_address:fd.get("location_address"),area_sq_ft:Number(fd.get("area_sq_ft")),property_value:Number(fd.get("property_value")),land_reference_code:fd.get("land_reference_code"),document_hash:documentHash}),"Property registered and confirmed on-chain.")}><Field label="Property ID"><Input name="property_id" type="number" min="1" required placeholder="1001"/></Field>{userSelect()}<Field label="Title"><Input name="title" required placeholder="Riverside Apartments"/></Field><Field label="Location"><Input name="location_address" required placeholder="Full property address"/></Field><Field label="Area (sq ft)"><Input name="area_sq_ft" type="number" min="1" step="any" required/></Field><Field label="Property Value"><Input name="property_value" type="number" min="0.01" step="0.01" required/></Field><Field label="Land Reference Code"><Input name="land_reference_code" required placeholder="LAND-MH-1001"/></Field><div className="md:col-span-2 grid gap-4 md:grid-cols-2"><Field label="Property Document"><Input name="document_file" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" required onChange={async event=>{const input=event.currentTarget;const file=input.files?.[0];setDocumentHash("");setDocumentName(file?.name||"");setNotice(null);if(!file)return;if(file.size>25*1024*1024){setDocumentName("");input.value="";setNotice({kind:"error",text:"Choose a document smaller than 25 MB."});return;}setHashing(true);try{if(!globalThis.crypto?.subtle)throw new Error("Secure hashing is unavailable");const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());setDocumentHash(Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join(""));}catch{setDocumentName("");input.value="";setNotice({kind:"error",text:"Could not hash this document in the browser. Try a smaller file or a secure browser connection."});}finally{setHashing(false);}}}/></Field><Field label="Document Hash (SHA-256)"><Input name="document_hash_preview" value={documentHash} readOnly required placeholder={hashing?"Calculating hash…":"Select a document to generate its hash"}/></Field><p className="text-xs muted md:col-span-2">{documentName?`Selected: ${documentName}. `:""}The file stays on this device; only its hash is sent to the database and blockchain.</p></div><div className="md:col-span-2"><button className="btn" disabled={loading||hashing||!documentHash}>{hashing?"Calculating document hash…":loading?"Submitting · Waiting for confirmation…":"Register Property"}</button></div></form></Panel>}
   {section==="Property Explorer"&&<Panel title="Property explorer" subtitle="Compare live PostgreSQL records with the current LandChain deployment"><form className="mb-6 flex max-w-xl gap-3" onSubmit={e=>handle(e,fd=>request(`/properties/${fd.get("property_id")}/inspect`),"Inspection completed.")}><Input name="property_id" type="number" min="1" required placeholder="Property ID, e.g. 1001"/><button className="btn shrink-0" disabled={loading}>Inspect</button></form>{properties.length>0&&<div className="table-wrap"><table className="w-full"><thead><tr><th>ID</th><th>Property</th><th>Location</th><th>Verification</th><th>Tokens</th></tr></thead><tbody>{properties.map(row)}</tbody></table></div>}<p className="mt-4 text-xs muted">Results list the exact fields that differ when database and chain state are inconsistent.</p></Panel>}
   {section==="Verify Property"&&<Panel title="Verify property" subtitle="Verification is committed on-chain before PostgreSQL is updated"><div className="mb-5 rounded-xl border border-white/5"><div className="table-wrap"><table className="w-full"><thead><tr><th>ID</th><th>Property</th><th>Owner</th><th>Action</th></tr></thead><tbody>{properties.filter(p=>p.blockchain_registered&&!p.blockchain_verified).map(p=><tr key={p.id}><td>#{p.property_id}</td><td>{p.title}</td><td>{users.find(u=>u.id===p.owner_user_id)?.full_name||"—"}</td><td><button className="btn !px-3 !py-2 text-xs" disabled={loading} onClick={()=>void run(()=>submit(`/properties/${p.property_id}/verify`,{}),`Property #${p.property_id} verified.`)}>Verify</button></td></tr>)}</tbody></table></div>{!properties.some(p=>p.blockchain_registered&&!p.blockchain_verified)&&<div className="p-6 text-center text-sm muted">No registered unverified properties.</div>}</div></Panel>}
   {section==="Ownership Transfer"&&<Panel title="Transfer property ownership" subtitle="Backend signer must match the current blockchain owner"><form className="grid max-w-2xl gap-4 md:grid-cols-2" onSubmit={e=>handle(e,fd=>submit(`/properties/${fd.get("property_id")}/transfer`,{new_owner:fd.get("new_owner")}),"Ownership transferred on-chain and synchronized.")}>{transferSelect()}<Field label="New Owner Address"><Input name="new_owner" required placeholder="Registered user's wallet address"/></Field><div><button className="btn" disabled={loading}>{loading?"Transferring…":"Transfer Ownership"}</button></div></form></Panel>}
   {section==="Tokenize Asset"&&<Panel title="Tokenize verified property" subtitle="Deploy a property-specific ERC-20 contract with whole-number shares"><form className="grid max-w-3xl gap-4 md:grid-cols-2" onSubmit={e=>handle(e,fd=>submit(`/properties/${fd.get("property_id")}/tokenize`,{token_name:fd.get("token_name"),symbol:fd.get("symbol"),total_supply:Number(fd.get("total_supply")),price_per_token:Number(fd.get("price_per_token"))}),"Token deployed and saved.")}>{propSelect("Verified Property")}<Field label="Token Name"><Input name="token_name" required placeholder="Riverside Shares"/></Field><Field label="Token Symbol"><Input name="symbol" required maxLength={16} placeholder="RIV"/></Field><Field label="Total Supply"><Input name="total_supply" type="number" min="1" step="1" required placeholder="10000"/></Field><Field label="Price Per Token"><Input name="price_per_token" type="number" min="0.01" step="0.01" required placeholder="250"/></Field><div><button className="btn" disabled={loading}>{loading?"Deploying token…":"Tokenize Property"}</button></div></form></Panel>}
   {section==="Token Portfolio"&&<Panel title="Token portfolio" subtitle="Read the current wallet balance directly from the token contract"><form className="mb-6 grid max-w-2xl gap-4 md:grid-cols-[1fr_1fr_auto]" onSubmit={e=>handle(e,fd=>request(`/tokens/${fd.get("property_id")}/balance?wallet=${encodeURIComponent(String(fd.get("wallet")))}`),"Balance loaded from blockchain.")}>{transferSelect()}<Field label="Wallet Address"><Input name="wallet" required placeholder="0x…"/></Field><button className="btn self-end" disabled={loading}>Check Balance</button></form><div className="grid gap-4 sm:grid-cols-2">{properties.filter(p=>p.tokenized).map(p=><div key={p.id} className="rounded-xl border border-white/5 bg-white/[.025] p-4"><div className="text-xs muted">Property #{p.property_id}</div><div className="mt-1 font-medium">{p.title}</div><div className="mt-3 break-all text-xs text-emerald-200">{p.token_contract_address}</div></div>)}</div></Panel>}
   {section==="Token Transfer"&&<Panel title="Transfer property tokens" subtitle="The backend signer must correspond to the sender wallet"><form className="grid max-w-3xl gap-4 md:grid-cols-2" onSubmit={e=>handle(e,fd=>submit(`/tokens/${fd.get("property_id")}/transfer`,{sender:fd.get("sender"),recipient:fd.get("recipient"),amount:Number(fd.get("amount"))}),"Token transfer confirmed on-chain.")}>{transferSelect()}<Field label="Sender"><Input name="sender" required placeholder="Signer wallet address"/></Field><Field label="Recipient"><Input name="recipient" required placeholder="Recipient wallet address"/></Field><Field label="Amount (whole shares)"><Input name="amount" type="number" min="1" step="1" required/></Field><div className="md:col-span-2"><button className="btn" disabled={loading}>{loading?"Waiting for confirmation…":"Transfer Tokens"}</button></div></form></Panel>}
   <footer className="mt-10 flex flex-wrap justify-between gap-3 border-t border-white/5 pt-5 text-xs muted"><span>LandChain · {activeNetwork}</span><span>API {health?.backend==="ok"?"● Online":"○ Offline"}</span></footer>
  </main>
 </div>
}
